### ISSUE TITLE
Using no user interface

### ISSUE THREAD

**Issue by furesoft** [dbforge/nUpdate#94]
in the readme is a section called "Using no user interface" but the nuget package depends on System.Windows.Forms that cant be found

**Comment by dbforge** [comment]
Yet another problem caused by the project structure and low cohesion.
I would need to abstract the user interface and outsource it (using separate projects), just like im version 4. The problem is that this would require 8 different projects as each (WinForms, WPF and no ui) would need an implementation for TAP and EAP exclusively.

I am thinking about abandoning the WithoutTAP package and set on TAP only (as it is the state-of-the-art pattern anyway).
Still would have to rely on the Bcl-package (or make nUpdate base on .NET >= 4.5, which would result in a major change actually).

I will think about it.
